name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish Blazor client
        run: dotnet publish ./WorldConquestGame.Client/WorldConquestGame.Client.csproj -c Release -o ./publish/Client

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          # Use root location since portal is overriding app_location anyway
          app_location: "/"
          api_location: ""
          # Point directly to the published wwwroot folder
          app_artifact_location: "publish/Client/wwwroot"
          skip_app_build: true
