name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish Blazor client
        run: dotnet publish ./WorldConquestGame.Client/WorldConquestGame.Client.csproj -c Release -o ./publish/Client

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations
          action: "upload"
          # Point to the Blazor client project so Oryx can detect .NET correctly.
          # This helps avoid platform-detection failures even when skip_app_build=true.
          app_location: "WorldConquestGame.Client"
          api_location: "" # no Azure Functions API in this repo
          app_artifact_location: "publish/Client/wwwroot" # the folder containing index.html after dotnet publish
          skip_app_build: true
