name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish Blazor client
        # Build the Blazor WebAssembly client with .NET 8 and output static files
        run: dotnet publish WorldConquestGame.Client/WorldConquestGame.Client.csproj -c Release -o ./publish_client

      - name: Show publish artifact contents (diagnostic)
        run: |
          echo "==== Listing publish_client/wwwroot (top) ===="
          ls -la publish_client/wwwroot || true
          echo "==== Listing publish_client/wwwroot/_framework (top) ===="
          ls -la publish_client/wwwroot/_framework || true
          echo "==== index.html head ===="
          head -n 120 publish_client/wwwroot/index.html || true

  # Let the Static Web Apps action build the Blazor client project directly.

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Use the configured Victorious secret for the SWA deployment token
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_DUNE_0AFCA7C03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations
          action: "upload"
          # We're uploading a pre-built artifact produced by the publish step above.
          # Use the upload action inputs: app_location is the app root (use "/") and
          # app_artifact_location points to the folder that contains index.html.
          app_location: "/"
          app_artifact_location: "publish_client/wwwroot"
          api_location: "" # no Azure Functions API in this repo
          skip_app_build: true
